inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - coconductor.gemspec

Layout/LineLength:
  Exclude:
    - lib/coconductor/project_files.rb
    - lib/coconductor/commands/*
    - script/vendor-codes-of-conduct

Metrics/ClassLength:
  Exclude:
    - lib/coconductor/code_of_conduct.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/coconductor/commands/*

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/coconductor/commands/*

Metrics/AbcSize:
  Exclude:
    - lib/coconductor/commands/*

Metrics/MethodLength:
  Exclude:
    - lib/coconductor/commands/*
